export { default as AboutPage } from './aboutPage'
export { default as ConnectPage } from './connectPage'
export { default as HomePage } from './HomePage'
export { default as ExplorePage } from './explorePage'
export { default as SignupPage } from './Signup'
export { default as LoginPage } from './Login'
export { default as ForgotPasswordPage } from './ForgotPassword'
export { default as SignupDetailsPage} from './signupDetailsPage'
export { default as SinglePost} from './singlePost'
export { default as TextTest} from './textTest'
export { default as ProjectView} from './projectView'
export { default as ProjectComponentView} from './projectComponentView'